name: 'Prepare App Runner'
description: 'Prepare App Runner for Deployment'
author: 'Bervianto Leo Pratama'
inputs:
  arn: # change this
    required: true
    description: 'App Service ARN'
  region:
    required: true
    description: 'AWS Region'
  wait:
    required: false
    description: 'Waiting time in seconds'
    default: '30'
runs:
  using: 'node20'
  main: 'dist/index.js'
  post: 'dist/post/index.js'
